circle:
  [
    [7, 12, 3],
    [46, 20, 2],
    [15, 5, 2],
    [37, 7, 3],
    [37, 23, 3]
  ]

rectangle:
  [
    [14, 12, 8, 2],
    [18, 22, 8, 3],
    [26, 7, 2, 12],
    [32, 14, 10, 2]
  ]

boundary:
  [
    [0, 0, 1, 30],
    [0, 30, 50, 1],
    [1, 0, 50, 1],
    [50, 1, 1, 30]
  ]